// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package cron_gql

type AddJobInput struct {
	CronExp      string `json:"cronExp"`
	AbsolutePath string `json:"absolutePath"`
	ShellCmd     string `json:"shellCmd"`
}

type Job struct {
	EntryID      string  `json:"entryId"`
	NextTime     *string `json:"NextTime"`
	PreviousTime *string `json:"PreviousTime"`
}
